first@Sanchit|second@Samuel|phone@9650649764|address@23 Railway|other@lol|
first@Sameer|second@Samuel|phone@654321|address@23 Railway|
first@Ankit|second@Masih|phone@123456|address@22 champa|others@oppes|
first@Arpit|second@Moi|phone@1234|address@23 Ooty|other@dude|
first@Andrew|second@Angels|phone@1993|address@1 Rajiv Chowk|others@daru|
first@t|second@t3|phone@123|address@t1|other@t2|
first@no|second@no|phone@124|address@|other@|
